[files]
extend-exclude = ["docs/versioned"] # don't check ./docs/versioned

[default]
locale = "en-us"

[default.extend-identifiers]
FilterThreshhold = "FilterThreshhold" # ignore error, it is actually "Paper.FilterThreshhold" in Paper

[default.extend-words]
accessorise = "accessorize"
aluminium = "aluminum"
analyse = "analyze"
armour = "armor"
authorise = "authorize"
authorised = "authorized"
authorising = "authorizing"
catalogue = "catalog"
centre = "center"
civilisation = "civilization"
civilised = "civilized"
colour = "color"
colours = "colors"
defence = "defense"
gramme = "gram"
grammes = "grams"
grey = "gray"
honour = "honor"
honours = "honors"
kerb = "curb"
kerbs = "curbs"
labour = "labor"
licence = "license"
licences = "licenses"
manoeuvre = "maneuver"
manoeuvres = "maneuvers"
metre = "meter"
metres = "meters"
modelled = "modeled"
neighbour = "neighbor"
neighbours = "neighbors"
neighbouring = "neighboring"
organisation = "organization"
organise = "organize"
organised = "organized"
organising = "organizing"
practise = "practice"
practised = "practiced"
practising = "practicing"
recognise = "recognize"
recognised = "recognized"
recognising = "recognizing"
routeing = "routing"
serialise = "serialize"
serialiser = "serializer"
serialising = "serializing"
deserialise = "deserialize"
deserialiser = "deserializer"
deserialising = "deserializing"
tonne = "ton"
tonnes = "tons"
traveller = "traveler"
travelling = "traveling"

# British spelling is wanted here for consistency with Folia code
regionize = "regionise"
regionizer = "regioniser"
regionizing = "regionising"
regionized = "regionised"
