[files]
extend-exclude = [
  "public/d2" # D2 output shouldn't be checked
]

[default]
locale = "en-us"
extend-ignore-re = [
  # {/* spellchecker:<on|off> */}
  "(?s)\\{/\\*\\s*spellchecker:off\\s*\\*/\\}.*?\\n\\s*\\{/\\*\\s*spellchecker:on\\s*\\*/\\}"
]

[default.extend-identifiers]
Spectre = "Spectre" # ignore error, the vulnerability is named Spectre

[default.extend-words]
accessorise = "accessorize"
aluminium = "aluminum"
analyse = "analyze"
armour = "armor"
authorise = "authorize"
authorised = "authorized"
authorising = "authorizing"
behaviour = "behavior"
capitalise = "capitalize"
catalogue = "catalog"
centre = "center"
civilisation = "civilization"
civilised = "civilized"
colour = "color"
colours = "colors"
defence = "defense"
generalise = "generalize"
generalised = "generalized"
gramme = "gram"
grammes = "grams"
grey = "gray"
honour = "honor"
honours = "honors"
initialise = "initialize"
initialised = "initialized"
initialiser = "initializer"
kerb = "curb"
kerbs = "curbs"
labour = "labor"
licence = "license"
licences = "licenses"
manoeuvre = "maneuver"
manoeuvres = "maneuvers"
metre = "meter"
metres = "meters"
modelled = "modeled"
neighbour = "neighbor"
neighbours = "neighbors"
neighbouring = "neighboring"
optimise = "optimize"
optimised = "optimized"
optimisation = "optimization"
organisation = "organization"
organise = "organize"
organised = "organized"
organising = "organizing"
practise = "practice"
practised = "practiced"
practising = "practicing"
recognise = "recognize"
recognised = "recognized"
recognising = "recognizing"
routeing = "routing"
serialise = "serialize"
serialiser = "serializer"
serialising = "serializing"
deserialise = "deserialize"
deserialiser = "deserializer"
deserialising = "deserializing"
tonne = "ton"
tonnes = "tons"
traveller = "traveler"
travelling = "traveling"
regionise = "regionize"
regioniser = "regionizer"
regionising = "regionizing"
regionised = "regionized"

# exceptions:

# use British spelling to stay consistent with Bukkit
canceled = "cancelled"
canceling = "cancelling"
cancelable = "cancellable"
cancelation = "cancellation"
