[files]
extend-exclude = [
    "docs/versioned", # old documentation shouldn't be checked
    "*.json"          # mostly configuration, not worth checking
]

[default]
locale = "en-us"

[default.extend-identifiers]
FilterThreshhold = "FilterThreshhold" # ignore error, it is actually "Paper.FilterThreshhold" in Paper
ERR_CANCELED = "ERR_CANCELED" # axios error enum

[default.extend-words]
accessorise = "accessorize"
aluminium = "aluminum"
analyse = "analyze"
armour = "armor"
authorise = "authorize"
authorised = "authorized"
authorising = "authorizing"
catalogue = "catalog"
centre = "center"
civilisation = "civilization"
civilised = "civilized"
colour = "color"
colours = "colors"
defence = "defense"
gramme = "gram"
grammes = "grams"
grey = "gray"
honour = "honor"
honours = "honors"
kerb = "curb"
kerbs = "curbs"
labour = "labor"
licence = "license"
licences = "licenses"
manoeuvre = "maneuver"
manoeuvres = "maneuvers"
metre = "meter"
metres = "meters"
modelled = "modeled"
neighbour = "neighbor"
neighbours = "neighbors"
neighbouring = "neighboring"
optimise = "optimize"
optimised = "optimized"
optimisation = "optimization"
organisation = "organization"
organise = "organize"
organised = "organized"
organising = "organizing"
practise = "practice"
practised = "practiced"
practising = "practicing"
recognise = "recognize"
recognised = "recognized"
recognising = "recognizing"
routeing = "routing"
serialise = "serialize"
serialiser = "serializer"
serialising = "serializing"
deserialise = "deserialize"
deserialiser = "deserializer"
deserialising = "deserializing"
tonne = "ton"
tonnes = "tons"
traveller = "traveler"
travelling = "traveling"
regionise = "regionize"
regioniser = "regionizer"
regionising = "regionizing"
regionised = "regionized"

# exceptions:

# use British spelling to stay consistent with Bukkit
canceled = "cancelled"
canceling = "cancelling"
cancelable = "cancellable"
cancelation = "cancellation"
