settings:
  allow-end:
    default: "true"
    description: Whether to load end-type dimensions.
  warn-on-overload:
    default: "true"
    description: Allows disabling the "Can't keep up!" message.
  permissions-file:
    default: permissions.yml
    description: >-
      File to load server permissions from. Use of this feature has mostly been
      replaced by permission plugins.
  update-folder:
    default: update
    description: >-
      Path to replace new plugin versions with.
      See [Updating Plugins](/paper/updating#step-2-update-plugins) for more information.
  plugin-profiling:
    default: "false"
    description: "This option does not operate, as it is disabled by a Paper patch."
  connection-throttle:
    default: "4000"
    description: >-
      How long of a delay to enforce between connections from an IP address.
      Measured in milliseconds since last attempt.
  query-plugins:
    default: "true"
    description: Whether to send plugins in the GS4 Query protocol response.
  deprecated-verbose:
    default: default
    description: >
      Whether to warn for use of deprecated events. If "default", the warning is
      printed if annotated with `@Warning(true)`. Ignored if system property
      [paper.alwaysPrintWarningState](/paper/reference/system-properties#paperalwaysprintwarningstate)
      is true.

      Valid values are "true", "false", or "default".
  shutdown-message:
    default: Server closed
    description: |
      The kick message for the player when the server shuts down.
      The message is formatted with legacy "ยง" style formatting.
  minimum-api:
    default: none
    description: >
      Minimum plugin [api-version](/paper/dev/plugin-yml#api-version). A string
      containing the server version, from `1.13` to `\{LATEST_PAPER_RELEASE}`. If
      below this, or not specified, the plugin is prevented from loading.
  use-map-color-cache:
    default: "true"
    description: >-
      Whether to build and save mappings from RGB colors to the closest map
      palette color.
  world-container:
    default: "N/A"
    description: >-
      Specifies the path to the folder where world files are saved. By default, this is the folder where the server JAR file is located.
      Note: Worlds must be manually moved to this folder for the server to recognize them.
spawn-limits:
  monsters:
    default: "70"
    description: >-
      Set the spawn-limits for monsters. This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_monster).
  animals:
    default: "10"
    description: >-
      Set the spawn-limits for animals. This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_creature).
  water-animals:
    default: "5"
    description: >-
      Set the spawn-limits for water animals. This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_water_creature).
  water-ambient:
    default: "20"
    description: >-
      Set the spawn-limits for water ambient mobs. This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_water_ambient).
  water-underground-creature:
    default: "5"
    description: >-
      Set the spawn-limits for water underground creatures. This can be
      overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_underground_water_creature).
  axolotls:
    default: "5"
    description: >-
      Set the spawn-limits for axolotls. This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_axolotls).
  ambient:
    default: "15"
    description: >-
      Set the spawn-limits for ambient mobs. This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_ambient).
chunk-gc:
  period-in-ticks:
    default: "600"
    description: >-
      How long chunks loaded by plugins should last for. Capped by Paper to be
      20 ticks (1 second).
ticks-per:
  animal-spawns:
    default: "400"
    description: >-
      Number of ticks between each passive creature (animal) spawn attempt.
      Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Spawn_limit).
      This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_creature).
  monster-spawns:
    default: "1"
    description: >-
      Number of ticks between each hostile monster spawn attempt.
      Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Spawn_limit).
      This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_monster).
  water-spawns:
    default: "1"
    description: >-
      Number of ticks between each water creature spawn attempt.
      Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Spawn_limit).
      This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_water_creature).
  water-ambient-spawns:
    default: "1"
    description: >-
      Number of ticks between each ambient water mob spawn attempt.
      Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Spawn_limit).
      This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_water_ambient).
  water-underground-creature-spawns:
    default: "1"
    description: >-
      Number of ticks between each underground water creatures spawn attempt.
      Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Spawn_limit).
      This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_underground_water_creature).
  axolotl-spawns:
    default: "1"
    description: >-
      Number of ticks between each axolotl spawn attempt.
      Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Spawn_limit).
      This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_axolotls).
  ambient-spawns:
    default: "1"
    description: >-
      Number of ticks between each ambient mob spawn attempt.
      Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Spawn_limit).
      This can be overridden by the
      [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_ambient).
  autosave:
    default: "6000"
    description: >-
      Number of ticks between each full auto-save. Set to -1 to disable
      auto-save.
aliases:
  default: now-in-commands.yml
  description: Static value from converting old versions to the new commands.yml format.
worlds:
  <world>:
    biome-provider:
      default: "N/A"
      description: >-
        The biome provider to use for this world. Plugins must register a `BiomeProvider`
        to be used here. The format is *plugin-name:extra-parameters* or *plugin-name*
        if no extra parameters are needed. The plugin name is as defined in the
        `plugin.yml` or `paper-plugin.yml`.
    generator:
      default: "N/A"
      description: >-
        The generator to use for this world. Plugins must register a `ChunkGenerator`
        to be used here. The format is *plugin-name:extra-parameters* or
        *plugin-name* if no extra parameters are needed. The plugin name is as defined
        in the `plugin.yml` or `paper-plugin.yml`.
