command-block-overrides:
  default: "[<command to override>]"
  description: >
    Which Vanilla commands should be prioritized over those provided by Bukkit
    or plugins. Useful for compatibility with adventure maps built for Vanilla
    command blocks.

    Use the literal ''*'' to always use the Vanilla version in command blocks.

    By default, no commands are overridden.
ignore-vanilla-permissions:
  default: "false"
  description: Whether to use Vanilla permission levels when executing commands.
aliases:
  icanhasbukkit:
    default: "[version $1-]"
    description: >-
      A built-in alias. Set aliases to an empty list ([]) to persistently remove.
  <alias name>:
    default: "[<commands to run>]"
    description: >
      A list of strings which are target commands. Alternatively, a string,
      which is a single target command.

      A target command is a command that is run, when the alias is run.

      Replacements:

        * `$sender` is replaced with the command sender''s name (Added by Paper).
        * `$<n>` is replaced by the n''th argument, 1-indexed.
        * `$$<n>` is replaced by the n''th argument, 1-indexed, failing if the n''th argument is not present.
        * `$<n>-` is replaced by the n''th argument and everything that follows, 1-indexed.
        * `$$<n>-` is replaced by the n''th argument and everything that follows, 1-indexed, failing if the n''th argument is not present.


      Each alias registered cannot (easily) be overridden by a plugin.
