accept-transfers:
  default: "false"
  description: "Whether this server accepts transfers from other servers using the transfer command/packet. If this is set to false, the server will disconnect the client."
allow-flight:
  default: "false"
  description: >
    Means that users will not be kicked if they fly whilst in Survival mode. This is likely to occur through
    hacking however there can be false positives.
broadcast-console-to-ops:
  default: "true"
  description: "Send console command output to all online operators."
broadcast-rcon-to-ops:
  default: "true"
  description: "Send rcon command output to all online operators."
bug-report-link:
  default: ""
  description: "A URL value used for the Report Server Bugs button in the Server Links client menu."
debug:
  default: "false"
  description: "Enables the server's debug mode."
difficulty:
  default: "easy"
  description: 'Defines the difficulty of the server. (Allowed values: "peaceful", "easy", "normal", "hard")'
enable-code-of-conduct:
  default: "false"
  description: >-
    Whether the server will look for code of conduct files in the codeofconduct subfolder in the server folder.

    Each file in the folder should have the form <language_code>.txt. The server will then show the code of conduct
    matching the player’s language. If the language doesn’t exist, then en_us will be used. If neither exist, an
    arbitrary available entry will be used instead.
enable-jmx-monitoring:
  default: "false"
  description: >
    Exposes an MBean with the Object name "net.minecraft.server:type=Server" and two attributes
    "averageTickTime" and "tickTimes" exposing the tick times in milliseconds. In order for enabling JMX on
    the Java runtime you also need to add a couple of JVM flags to the startup as documented
    [here](https://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html)
enable-query:
  default: "false"
  description: "Enables GameSpy4 protocol server listener. Used to get information about server."
enable-rcon:
  default: "false"
  description: "Enables remote access to the server console."
enable-status:
  default: "true"
  description: >
    Makes the server appear on the server list and also enables listener for getting server
    information. If turned off, server will appear offline but players will still be able to connect.
enforce-secure-profile:
  default: "true"
  description: "If set to true, players without a Mojang-signed public key will not be able to connect to the server."
enforce-whitelist:
  default: "false"
  description: "If set to true, the server will kick players who are not on the whitelist."
entity-broadcast-range-percentage:
  default: "100"
  description: >
    Controls how close entities need to be before being sent to clients. Higher values means they''ll
    be rendered from farther away, potentially causing more lag. This is expressed the percentage of the default
    value. For example, setting to 50 will make it half as usual. This mimics the function on the client video
    settings (not unlike Render Distance, which the client can customize so long as it''s under the server''s
    setting). This must be between 10 and 1000 percent.
force-gamemode:
  default: "false"
  description: >
    Force players to join in the default game mode. This will reset their previous game mode when they
    reconnect.
function-permission-level:
  default: "2"
  description: "Sets the default permission level for functions. (Allowed values: 1, 2, 3, 4)"
gamemode:
  default: "survival"
  description: 'Defines the mode of gameplay. (Allowed values: "survival", "creative", "adventure", "spectator")'
generate-structures:
  default: "true"
  description: "Defines whether structures (such as villages) will be generated."
generator-settings:
  default: "{}"
  description: >
    The settings used to customize world generation. Follow
    [its format](https://minecraft.wiki/w/Java_Edition_level_format#generatorOptions_tag_format) and
    write the corresponding JSON string.
hardcore:
  default: "false"
  description: "If set to true, players will be set to spectator mode if they die."
hide-online-players:
  default: "false"
  description: "Hides the player list sent with the status request packets."
initial-disabled-packs:
  default: ""
  description: "Comma-separated list of datapacks to not be auto-enabled on world creation."
initial-enabled-packs:
  default: "vanilla"
  description: >
    Comma-separated list of datapacks to be enabled during world creation. Feature packs need
    to be explicitly enabled.
level-name:
  default: "world"
  description: "The name of the world. This will be the name of the folder in which the world is saved."
level-seed:
  default: ""
  description: "The seed used to generate the world. Leave blank to default to random."
level-type:
  default: "minecraft:normal"
  description: >
    Defines the type of the world generator. (Allowed values: "normal", "flat", "large_biomes",
    "amplified", "single_biome_surface", "buffet", "default_1_1", "customized")
log-ips:
  default: "true"
  description: >-
    Whether player IP addresses should be logged by the server. This does not
    impact the ability of plugins to log the IP addresses of players
management-server-enabled:
  default: "false"
  description: "Whether the [Minecraft Server Management Protocol](https://minecraft.wiki/w/Minecraft_Server_Management_Protocol) is enabled."
management-server-host:
  default: "localhost"
  description: "Controls the host that the Minecraft Server Management Protocol is started."
management-server-port:
  default: "localhost"
  description: "Controls the port that the Minecraft Server Management Protocol is started on."
management-server-secret:
  default: ""
  description: >-
    Allows for clients to supply an Authorization header with a server specific secret, which is forty alphanumeric characters long (A-Z, a-z, and 0-9).

    The secret is automatically generated if the property is left empty.
management-server-tls-enabled:
  default: "true"
  description: "Controls whether the Minecraft Server Management Protocol uses TLS (Transport Layer Security)."
management-server-tls-keystore:
  default: ""
  description: >-
    Controls the path to the keystore file used for TLS.

    A server will not start is TLS is enabled and no keystore is provided.
management-server-tls-keystore-password:
  default: ""
  description: >-
    Controls the password to the keystore file used for TLS.

    The password can be done through an environment variable (MINECRAFT_MANAGEMENT_TLS_KEYSTORE_PASSWORD), a
    Java Virtual Machine argument (-Dmanagement.tls.keystore.password=), or through this server property.
max-chained-neighbor-updates:
  default: "1000000"
  description: >
    Limits the number of consecutive neighbor updates before skipping subsequent updates. Negative
    values will disable the limit.
max-players:
  default: "20"
  description: "The maximum number of players that can play on the server at the same time."
max-tick-time:
  default: "60000"
  description: >
    The maximum number of milliseconds a single tick may take before the server watchdog stops the
    server with the message. If a single server tick took 60.00 seconds (should be max 0.05) it will be considered to be
    crashed and the server will forcibly shutdown via calling System.exit(1). Setting this to -1 will disable watchdog
    entirely.
max-world-size:
  default: "29999984"
  description: >
    The maximum allowed size of the world radius, in blocks. This only affects the chunks that are
    generated when the world is initially created, and not the world border (Limited to 29999984).
motd:
  default: "A Minecraft Server"
  description: "The message of the day, displayed in the server list."
network-compression-threshold:
  default: "256"
  description: "The number of bytes of a packet before it is compressed. Setting to a negative disables compression."
online-mode:
  default: "true"
  description: >
    If set to true, the server checks all connecting players against Minecraft''s account database.
    This requires all connected players to have a valid Minecraft account and makes it impossible for cracked
    players to connect.
op-permission-level:
  default: "4"
  description: "Sets the default permission level for ops when using /op. (Allowed values: 0, 1, 2, 3, 4)"
pause-when-empty-seconds:
  vanilla: "60"
  default: "-1"
  description: >
    How many seconds have to pass after no player has been online before the server is paused.
    This is disabled by default because it is incompatible with what plugins expect and might do with no players online.
player-idle-timeout:
  default: "0"
  description: >
    If non-zero, players are kicked from the server if they are idle for more than that many minutes.
    (Default: 0). The following packets stop this timer: "Click Window", "Enchant Item", "Update Sign",
    "Player Digging", "Player Block Placement", "Held Item Change", "Animation (swing arm)", "Entity Action",
    "Client Status", "Chat Message", "Use Entity".
prevent-proxy-connections:
  default: "false"
  description: >
    If the ISP/AS sent from the server is different from the one from Mojang Studios'' authentication
    server, the player not allowed to join the server.
query.port:
  default: "25565"
  description: "The port for the query server. This is used to get information about the server."
rate-limit:
  default: "0"
  description: >
    Sets the maximum allowed number of packets that can be sent before getting kicked. Setting this to 0
    disables the limit.
rcon.password:
  default: ""
  description: "The password for the rcon server."
rcon.port:
  default: "25575"
  description: "The port to start the rcon server on."
region-file-compression:
  default: "deflate"
  description: >
    Specifies the compression type used to compress region files. Possible values are: "deflate", "lz4" and "none".
    If set to "none", region files will take up significantly more disk space, but it might make sense together with filesystem-level compression.
require-resource-pack:
  default: "false"
  description: "If true, a player must have the given resource pack to connect. They will be kicked if they do not have it."
resource-pack:
  default: ""
  description: "The URL to the server's resource pack. "
resource-pack-id:
  default: ""
  description: "The UUID of the server resource pack to use."
resource-pack-prompt:
  default: ""
  description: "The message that is displayed when the client is prompted to download the resource pack."
resource-pack-sha1:
  default: ""
  description: >
    The hash of the resource pack, used for verification. This is recommended to be set to ensure
    players are downloading the correct pack.
server-ip:
  default: ""
  description: "The IP address to bind to. Leave blank to bind to all interfaces."
server-port:
  default: "25565"
  description: "The port to listen on for connections."
simulation-distance:
  default: "10"
  description: >
    Sets the maximum distance from players that living entities may be located in order to be
    updated by the server, measured in chunks in each direction of the player (radius, not diameter).
    If entities are outside this radius, then they will not be ticked by the server nor will they be
    visible to players. Must be between 3 and 32 inclusive.
spawn-protection:
  default: "16"
  description: >
    Used to determine the side length of the spawn protection. The formula of 2x+1 is used. A value of 1
    will result in a side length of 3 **blocks**. Setting this to 0 will disable spawn protection. There must be
    at least 1 operator to be enabled.
status-heartbeat-interval:
  default: "0"
  description: >-
    Controls the intervals in which the management server sends heartbeat notifications to connected clients.
    It is disabled by default.
sync-chunk-writes:
  default: "true"
  description: |
    Enables synchronous writing of chunk data. Has no effect on Paper by default, unless the corresponding system property is also set to true.
    See [the system properties reference](/paper/reference/system-properties#paperenable-sync-chunk-writes).
text-filtering-config:
  default: ""
  description: "The path to the text filtering configuration file. Leave blank to disable text filtering."
text-filtering-version:
  default: "0"
  description: |
    The version of the configuration format used for [`text-filtering-config`](#text_filtering_config).
    Valid values are 0 and 1.
use-native-transport:
  default: "true"
  description: "Provides a performance boost for Linux servers."
view-distance:
  default: "10"
  description: >
    Sets the amount of world data the server sends the client, measured in chunks in each direction
    of the player (radius, not diameter). It determines the server-side viewing distance (Default: 10, Min: 3,
    Max: 32).
white-list:
  default: "false"
  description: "Enables a whitelist on the server. If enabled, the server will only allow selected users to connect."
