name: "Build Artifact"

on:
  workflow_call:
    inputs:
      preview:
        description: "Is this a preview deployment?"
        default: false
        required: false
        type: boolean
      url:
        description: "Domain the deployment will be hosted on"
        required: false
        type: string
      baseurl:
        description: "Path where does are hosted on domain"
        required: false
        type: string

env:
  NODE_VERSION: "17"
  DEPLOY_PREVIEW: ${{ inputs.preview }}
  PREVIEW_URL: ${{ inputs.url }}
  PREVIEW_BASE_URL: ${{ inputs.baseurl }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Node ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "yarn"
      - name: "Install Dependencies"
        run: "yarn install --immutable"
      - name: "Build Docs"
        run: yarn build
      - name: "Upload HTML"
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: build/
          retention-days: 1
